### ISSUE TITLE
Fout in bewijs E_tm onbeslisbaar

### ISSUE THREAD

**Issue by pcoenen** [FHannes/ab-samenvatting#3]
Dat E_tm turing reduceerbaar is naar A_tm bewijst niet dat E_tm onbeslisbaar is.

**Comment by mathiasvh** [comment]
Klopt, er wordt beter het bewijs mbhv Rice uitgewerkt als alternatief bewijs

**Comment by FHannes** [comment]
Die statement hoorde niet bij het bewijs, die had erbuiten moeten staan zoals op andere plekken. Het bewijs was niet volledig, dus heb nog een lijntje toegevoegd.
